-- 코드를 입력하세요
# SELECT * FROM BOOK;
SELECT b.BOOK_ID, a.AUTHOR_NAME, DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK b, AUTHOR a
WHERE CATEGORY = '경제' AND a.AUTHOR_ID = b.AUTHOR_ID
ORDER BY PUBLISHED_DATE;
