# 59042  
-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
LEFT OUTER JOIN ANIMAl_INS AS I
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID ASC, O.NAME ASC


# 276035
SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS AS A, (
    SELECT SUM(CODE) AS FE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)AS B
WHERE B.FE&A.SKILL_CODE > 0
ORDER BY A.ID

# 131124
