-- SUM, MAX, MIN

-- 가장 비싼 상품 구하기
SELECT MAX(PRICE) AS MAX_PRICE FROM PRODUCT;

-- 최대값 구하기
SELECT MAX(DATETIME) AS 시간 FROM ANIMAL_INS;

-- 최솟값 구하기
SELECT MIN(DATETIME) AS 시간 FROM ANIMAL_INS;

-- 동물 수 구하기
SELECT COUNT(ANIMAL_ID) AS count FROM ANIMAL_INS;

-- 중복 제거하기
SELECT COUNT(DISTINCT NAME) AS count FROM ANIMAL_INS;

-- 가격이 제일 비싼 식품의 정보 출력하기
SELECT *
FROM FOOD_PRODUCT
WHERE
    PRICE = (
        SELECT MAX(PRICE)
        FROM FOOD_PRODUCT
    );

-- 조건에 맞는 아이템들의 가격의 총합 구하기
SELECT SUM(PRICE) AS TOTAL_PRICE
FROM ITEM_INFO
WHERE
    RARITY = 'LEGEND';

-- 물고기 종류별 대어 찾기
SELECT FI.ID AS ID, FNI.FISH_NAME AS FISH_NAME, FI.LENGTH AS LENGTH
FROM
    FISH_INFO AS FI
    JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH) IN (
        SELECT FISH_TYPE, MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY
            FISH_TYPE
    )
ORDER BY FI.ID ASC;

-- 잡은 물고기 중 가장 큰 물고기의 길이 구하기
-- CONCAT(..., ...) : 두 개 이상의 문자열을 합치는 함수
SELECT CONCAT(MAX(LENGTH), 'cm') AS MAX_LENGTH FROM FISH_INFO;