-- 코드를 작성해주세요
-- FISH_INFO 에서 잡은 BASS + SNAPPER 수 출력

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO i, FISH_NAME_INFO n
WHERE i.FISH_TYPE = n.FISH_TYPE AND i.FISH_TYPE IN (SELECT FISH_TYPE
                    FROM FISH_NAME_INFO
                    WHERE FISH_NAME = "BASS" OR FISH_NAME = "SNAPPER")
